nebo:
  app:
    jwt:
      header_token: X-Nebo-Access-Token
      header_refresh_token: X-Nebo-Refresh-Token
      secret_key: 5jhbfdjhbvdhjvdfous
      expiration: 60000
      refresh_expiration: 86400000