spring:
  datasource-tenantdb:
    jdbc-url: jdbc:mariadb://localhost:3306/tenantdb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  datasource-templatedb:
    jdbc-url: jdbc:mariadb://localhost:3306/templatedb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  datasource-reportdb:
    jdbc-url: jdbc:mariadb://localhost:3306/reportdb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      #      hibernate:
      #        dialect: org.hibernate.dialect.MariaDBDialect
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      id:
        new_generator_mappings: false
      type.preferred_instant_jdbc_type: TIMESTAMP
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  kafka:
    bootstrap: localhost:9092
    topic:
      user-raw-log: dbtenants.tenantdb.users
      session-raw-log: dbtenants.tenantdb.sessions
      file-data-raw-log: dbserver1.templatedb.file_datas
      template-raw-log: dbserver1.templatedb.templates
      print-log-raw-log: dbserver1.templatedb.print_logs
  redis:
    host: localhost
    port: 6379
  grpc:
    url: http://localhost:9090
nebo:
  default-user-id: 1
  app:
    jwt:
      header_token: X-Nebo-Access-Token
      header_refresh_token: X-Nebo-Refresh-Token
      secret_key: 5jhbfdjhbvdhjvdfous9586jgfn9854ongjk4354589t5bsddsuj4jbsj43jf3jsj4jnbjsk4tp4k08897h6fgo5
      expiration: 7200000
      refresh_expiration: 86400000
      session_oauth_id: JSESSIONID
    basic-auth:
      secret-key: c0xdfsv0j98c599c85c95438c59
  feign:
    url: http://localhost:8000
    connectTimeout: 30000
    readTimeout: 10000
    retry:
      maxAttempts: 2
      period: 2000
      maxPeriod: 5
