spring:
  datasource-tenantdb:
    jdbc-url: jdbc:mariadb://localhost:3306/tenantdb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  datasource-templatedb:
    jdbc-url: jdbc:mariadb://localhost:3306/templatedb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  datasource-reportdb:
    jdbc-url: jdbc:mariadb://localhost:3306/reportdb
    username: admin
    password: jfnjvfd943njcdnfda
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        id:
          new_generator_mappings: false
        type.preferred_instant_jdbc_type:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  kafka:
    bootstrap: localhost:9092
    topic:
      user-log: kafka.topic.user
      session-log: kafka.topic.session
      file-data-raw-log: kafka.topic.session
      template-raw-log: kafka.topic.session
      print-log: kafka.topic.session
  redis:
    host: localhost
    port: 6379
  grpc:
    url: http://localhost:9090

nebo:
  default-user-id: 1