spring:
  config:
    import: "optional:configserver:http://configserver:8088"
    activate:
      on-profile: production
---
spring:
  application:
    name: template
  config:
    import: "optional:configserver:http://localhost:8088"